#!/bin/bash
creatos(){
	read -e -p "project name: " pname
	#create project
	gcloud projects create $pname
	#get project number
	pnum=$(gcloud projects list --filter="${pname}" --format="value(PROJECT_NUMBER)")
	#link billing
	accid=$(gcloud alpha billing accounts list --format="value(ACCOUNT_ID)")
	gcloud alpha billing projects link $pname  --billing-account $accid
	#set current project active
	gcloud config set project $pname	
	#enable api
	gcloud services enable compute.googleapis.com
	#add firewall
	gcloud compute firewall-rules create firewall$pname --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:6666,udp:6666 --source-ranges=0.0.0.0/0
	#add member to main group to use image
	gcloud projects add-iam-policy-binding p-main \
	--member serviceAccount:$pnum@cloudservices.gserviceaccount.com  \
	--role roles/compute.imageUser	
	#create instance template
	gcloud beta compute instance-templates create "${pname}-template" --machine-type=f1-micro --network="projects/${pname}/global/networks/default" --network-tier=PREMIUM --maintenance-policy=MIGRATE  --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=http-server,https-server \
	--image=p-image-1-au --image-project=p-main --boot-disk-size=20GB --boot-disk-type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

	#create instance group
	gcloud compute instance-groups managed create "${pname}-au" --region "australia-southeast1" --template "${pname}-template" --size 8

	#set auto-scaling off
	gcloud beta compute instance-groups managed set-autoscaling "${pname}-au" --region "australia-southeast1" --cool-down-period "60" --max-num-replicas "10" --min-num-replicas "1" --target-cpu-utilization "0.6" --mode "off"
	}
creatos
